### ISSUE TITLE
crashes when changing channel in Adjust Image Tab

### ISSUE THREAD

**Issue by SaibotMagd** [sanderslab/magellanmapper#22] opened 2021-04-28 11:46 UTC
The error ocure every time when I try to change the channel to adjust the image colors. But only when I loaded my own data:
Before the crash it seems like the data are loaded correctly. I can see 2 channels and both images onto each other.

I run the GUI using a python script:
```
bash = run +  "--img " + \
"/home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d " + \
" --reg_suffixes nisslTIF_manuel_corrected.nii,annotationTIFs.nii " + \
" --roi_profile atlas"
os.system(bash)

```

This is the whole output till mag crashes:

```

root - INFO - Set filenames to ['/home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d'], current filename /home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d
root - INFO - Updating ROI profile for channel 0
root - INFO - Set default (channel 0) ROI profile: default,atlas
root - INFO - Set atlas profile to default
root - INFO - Set registered image suffixes to {<RegSuffixes.ATLAS: 1>: ['nisslTIF_manuel_corrected.nii', 'annotationTIFs.nii'], <RegSuffixes.ANNOTATION: 2>: None, <RegSuffixes.BORDERS: 3>: None}
root - INFO - setting up Matplotlib style default
root - INFO - applying theme DEFAULT
root - INFO - Loaded database from /home/tgottsch/.local/share/MagellanMapper/magmap.db
root - INFO - set multiprocessing start method to fork
root - INFO - Loading main image
root - INFO - filename: /home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d
root - INFO - filename_base: /home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d
root - INFO - Reading image metadata from /home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d_meta.yml
root - ERROR - /home/tgottsch/Atlas_project/magellanmapper/magmap/io/importer.py:515: UserWarning: Could not find metadata file '/home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d_meta.yml', will check NPZ format
  .format(path))
root - ERROR - /home/tgottsch/Atlas_project/magellanmapper/magmap/io/importer.py:521: UserWarning: Could not find metadata file '/home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d_meta.npz', skipping
  .format(path_npz))
root - INFO - Could not load image files for /home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d
root - INFO - [Errno 2] No such file or directory: '/home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d_image5d.npy'
root - INFO - Looking for files for multi-channel images matching the format: /home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d_ch_*
root - INFO - Using the given single file /home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d
root - INFO - [Errno Multipage file to import does not exist:] /home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d
root - INFO - Could not load /home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d, will fall back to any associated registered image
root - INFO - Loading image with SimpleITK: /home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d_nisslTIF_manuel_corrected.nii
root - INFO - Loading image with SimpleITK: /home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d_annotationTIFs.nii
root - ERROR - /home/tgottsch/Atlas_project/magellanmapper/magmap/io/sitk_io.py:218: UserWarning: MagellanMapper image metadata file not loaded; will fallback to /home/tgottsch/Atlas_project/magellanmapper/examples/gerbilNissl/backup/2d_nisslTIF_manuel_corrected.nii for metadata
  "{} for metadata".format(loaded_path))
root - INFO - set resolutions to [[29.20000076  1.          1.        ]]
root - INFO - generating colormaps from RGBA colors:
root - INFO -  [[0.81176471 0.88235294 0.83529412 1.        ]]
root - INFO - --------------------------------------------------------------------------------
root - INFO - 
root - INFO - set border to zeros
root - INFO - set border to [0. 0. 0.]
root - INFO - setting up Matplotlib style seaborn
root - INFO - applying theme DEFAULT
root - INFO - got None selected
root - INFO - no roi found
root - INFO - Changed channel to [0, 1]
root - INFO - camera: {'view': (0.0, 0.0, 1.0, array([0., 0., 0.])), 'roll': 0.0}
root - INFO - Scene activated with view: (0.0, 0.0, 1.0, array([0., 0., 0.])) roll: -175.0
root - INFO - using ROI offset [0, 0, 0], size of [100 100  12] (x,y,z)
root - INFO - Initiating ROI Editor
root - INFO - margin: None, savefig: png
root - INFO - zoom_levels: [1.         1.74729584] max_zoom: 2.796666666666667
root - INFO - 2D border: [0. 0. 0.]
root - INFO - z_overview: 0
root - INFO - plane xy downsampling factors by image: [1, 1, 1]
root - INFO - plane xy downsampling factors by image: [1, 1, 1]
root - INFO - 2D plot time: 0.45488786697387695
matplotlib.font_manager - WARNING - findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
matplotlib.font_manager - WARNING - findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
root - INFO - profiles from table:
root - INFO -  [['ROI', 'atlas', 0]]
root - INFO - [['ROI' 'atlas' '0']] 0
root - INFO - Updating ROI profile for channel 0
root - INFO - Set default (channel 0) ROI profile: default,atlas
root - INFO - generating colormaps from RGBA colors:
root - INFO -  [[0.81176471 0.88235294 0.83529412 1.        ]]
root - INFO -  profile not found, skipped
root - INFO - Set atlas profile to default
traits - ERROR - Exception occurred in traits notification handler for object: <magmap.gui.visualizer.Visualization object at 0x7fc379f62048>, trait: _imgadj_min, old value: -32768.0, new value: 0.0
Traceback (most recent call last):
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/site-packages/traits/trait_notifiers.py", line 522, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/site-packages/traits/trait_notifiers.py", line 484, in dispatch
    handler(*args)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/gui/visualizer.py", line 1175, in _adjust_img_min
    plot_ax_img = self._adjust_displayed_imgs(minimum=self._imgadj_min)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/gui/visualizer.py", line 1246, in _adjust_displayed_imgs
    chl=int(self._imgadj_chls), **kwargs)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/gui/roi_editor.py", line 958, in update_imgs_display
    plot_ax_imgs, imgi, self._channel, chl)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/gui/plot_editor.py", line 572, in get_plot_ax_img
    plot_ax_img = plot_ax_imgs[imgi][chl]
IndexError: list index out of range
traits - ERROR - Exception occurred in traits notification handler for object: <magmap.gui.visualizer.Visualization object at 0x7fc379f62048>, trait: _imgadj_chls, old value: 0, new value: 1
Traceback (most recent call last):
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/site-packages/traits/trait_notifiers.py", line 522, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/site-packages/traits/trait_notifiers.py", line 484, in dispatch
    handler(*args)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/gui/visualizer.py", line 1105, in update_imgadj_for_img
    self._imgadj_min = norm.vmin
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/site-packages/traits/trait_notifiers.py", line 476, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/site-packages/traits/trait_notifiers.py", line 550, in _notify_method_listener
    object, trait_name, old, new, listener
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/site-packages/traits/trait_notifiers.py", line 530, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/site-packages/traits/trait_notifiers.py", line 148, in _handle_exception
    raise excp
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/site-packages/traits/trait_notifiers.py", line 522, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/tgottsch/anaconda3/envs/mag/lib/python3.6/site-packages/traits/trait_notifiers.py", line 484, in dispatch
    handler(*args)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/gui/visualizer.py", line 1175, in _adjust_img_min
    plot_ax_img = self._adjust_displayed_imgs(minimum=self._imgadj_min)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/gui/visualizer.py", line 1246, in _adjust_displayed_imgs
    chl=int(self._imgadj_chls), **kwargs)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/gui/roi_editor.py", line 958, in update_imgs_display
    plot_ax_imgs, imgi, self._channel, chl)
  File "/home/tgottsch/Atlas_project/magellanmapper/magmap/gui/plot_editor.py", line 572, in get_plot_ax_img
    plot_ax_img = plot_ax_imgs[imgi][chl]
IndexError: list index out of range
Unhandled Python exception
Aborted
Out[37]: 34304
```

**Comment by SaibotMagd** [comment] 2021-04-28 12:35
Update: It also crashes when I use the example files in the protocol

```
bash = run + \
        " --img " + main_path + example_path + sample_brain + "brain_fullatlas " + \
        " --reg_suffixes exp.mhd,atlasVolumePrecur.mhd" + \
        " --roi_profile norm --vmax 0.6,0.5 --vmin 0,0" + \
        " --plot_labels alphas_chl=1,0.3"
os.system(bash)
```

**Comment by yoda-vid** [comment] 2021-04-29 07:54
That is indeed a bug--thanks for another catch, @SaibotMagd!

I can reproduce it in the ROI Editor when the ROI set to the bottom or top of the image so that the zoomed ROI images include padding planes (the grayed out planes). Changing to a higher channel in the image adjustment panel triggers this error because it's looking for a channel that doesn't exist for these images.

I've posted a fix, which is available through `git fetch; git checkout fix_channel_adjustment`. Could you see if it fixes the issue for you? Hopefully it works for your images as well.

**Comment by SaibotMagd** [comment] 2021-04-30 10:58
> I've posted a fix, which is available through `git fetch; git checkout fix_channel_adjustment`. Could you see if it fixes the issue for you? Hopefully it works for your images as well.

It seems to work. Thanks again. 

2 other remarks: 
- it deactivates the "auto adjust" button very often when I change the channel or even by scrolling through the slices
- I would love to see a "maximize window" button in the future. It seems so unusual not to have this:
Any other GUI:
![image](https://user-images.githubusercontent.com/67700096/116686105-a193f300-a9b3-11eb-9afc-59c45a67ae67.png)
 Mag:
![image](https://user-images.githubusercontent.com/67700096/116686204-c5573900-a9b3-11eb-8e19-2a01fcc7257c.png)

**Comment by yoda-vid** [comment] 2021-05-01 04:01
Glad the fix worked for you too! I will go ahead and merge in the fix. The merge will close this issue, but I will open up two new issues for the other areas you mentioned so that we can track them there.

For the color profiles, you can change the ROI profile to "atlas" to get a grayscale colormap (eg `--roi_profile atlas`). You can also adjust it in the GUI by going to the "Profiles" tab, selecting "ROI" profile and "atlas" as the name, clicking "Add profile", and then going back to the "ROI" tab and pressing "Redraw". I would like to build in a colormaps selector one of these days to make this easier to adjust.

**Closed** 2021-05-01 04:01 UTC
Labels: bug

**Comment by yoda-vid** [comment] 2021-05-01 04:24
I added your other issues as #24 and #25, thanks again!
